remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Rushil Gupta"
description: "Hi, I’m Rushil Gupta, a tech enthusiast passionate about robotics, artificial intelligence, and automation. I enjoy exploring and learning new technologies, with a strong curiosity for innovation and problem-solving."
